import { Award, Clock, Flame, Zap, Trophy, Star, Target, Coffee, Dumbbell, Brain, Rocket, Heart, Medal, Crown, Sparkles, Lightbulb, Smile, Laugh, Compass, Gem, Gift, GamepadIcon, Users } from 'lucide-react-native';
import { colors } from './theme';

export interface Achievement {
  id: string;
  title: string;
  description: string;
  icon: any;
  iconColor: string;
  requiredValue: number;
  type: 'sessions' | 'streak' | 'totalMinutes' | 'level' | 'totalSessions' | 'totalDays' | 'specialAction' | 'gameScore' | 'teamSessions' | 'teamMinutes';
  reward: number; // XP reward
  secret?: boolean; // If true, description will be hidden until unlocked
}

export const achievements: Achievement[] = [
  // 基本的な実績
  {
    id: 'first_session',
    title: '初めての集中',
    description: '最初のポモドーロセッションを完了する',
    icon: Clock,
    iconColor: colors.primary,
    requiredValue: 1,
    type: 'sessions',
    reward: 50,
  },
  {
    id: 'focus_master',
    title: '集中マスター',
    description: '10回のポモドーロセッションを完了する',
    icon: Target,
    iconColor: colors.secondary,
    requiredValue: 10,
    type: 'sessions',
    reward: 100,
  },
  {
    id: 'productivity_guru',
    title: '生産性の達人',
    description: '50回のポモドーロセッションを完了する',
    icon: Zap,
    iconColor: colors.warning,
    requiredValue: 50,
    type: 'sessions',
    reward: 250,
  },
  {
    id: 'productivity_legend',
    title: '生産性の伝説',
    description: '100回のポモドーロセッションを完了する',
    icon: Crown,
    iconColor: '#FFD700',
    requiredValue: 100,
    type: 'sessions',
    reward: 500,
  },
  
  // 連続記録関連
  {
    id: 'consistency_beginner',
    title: '継続の初心者',
    description: '3日間の連続記録を達成する',
    icon: Flame,
    iconColor: colors.error,
    requiredValue: 3,
    type: 'streak',
    reward: 75,
  },
  {
    id: 'consistency_pro',
    title: '継続のプロ',
    description: '7日間の連続記録を達成する',
    icon: Flame,
    iconColor: colors.error,
    requiredValue: 7,
    type: 'streak',
    reward: 150,
  },
  {
    id: 'consistency_master',
    title: '継続マスター',
    description: '14日間の連続記録を達成する',
    icon: Flame,
    iconColor: '#FF4500',
    requiredValue: 14,
    type: 'streak',
    reward: 300,
  },
  {
    id: 'consistency_legend',
    title: '継続の伝説',
    description: '30日間の連続記録を達成する',
    icon: Flame,
    iconColor: '#FF0000',
    requiredValue: 30,
    type: 'streak',
    reward: 500,
  },
  
  // 時間関連
  {
    id: 'time_wizard',
    title: 'タイムウィザード',
    description: '合計60分の集中時間を達成する',
    icon: Clock,
    iconColor: colors.primary,
    requiredValue: 60,
    type: 'totalMinutes',
    reward: 100,
  },
  {
    id: 'time_lord',
    title: 'タイムロード',
    description: '合計300分の集中時間を達成する',
    icon: Clock,
    iconColor: colors.success,
    requiredValue: 300,
    type: 'totalMinutes',
    reward: 200,
  },
  {
    id: 'time_master',
    title: 'タイムマスター',
    description: '合計1000分の集中時間を達成する',
    icon: Clock,
    iconColor: '#9370DB',
    requiredValue: 1000,
    type: 'totalMinutes',
    reward: 350,
  },
  {
    id: 'time_emperor',
    title: 'タイムエンペラー',
    description: '合計3000分の集中時間を達成する',
    icon: Clock,
    iconColor: '#4B0082',
    requiredValue: 3000,
    type: 'totalMinutes',
    reward: 500,
  },
  
  // レベル関連
  {
    id: 'level_up_beginner',
    title: 'レベルアップ初心者',
    description: 'レベル5に到達する',
    icon: Trophy,
    iconColor: colors.warning,
    requiredValue: 5,
    type: 'level',
    reward: 0, // No reward as leveling up already gives rewards
  },
  {
    id: 'level_up_intermediate',
    title: 'レベルアップ中級者',
    description: 'レベル10に到達する',
    icon: Trophy,
    iconColor: colors.warning,
    requiredValue: 10,
    type: 'level',
    reward: 0,
  },
  {
    id: 'level_up_advanced',
    title: 'レベルアップ上級者',
    description: 'レベル20に到達する',
    icon: Trophy,
    iconColor: '#FFD700',
    requiredValue: 20,
    type: 'level',
    reward: 0,
  },
  {
    id: 'level_up_master',
    title: 'レベルアップマスター',
    description: 'レベル30に到達する',
    icon: Trophy,
    iconColor: '#FFD700',
    requiredValue: 30,
    type: 'level',
    reward: 0,
  },
  
  // 休憩関連
  {
    id: 'coffee_break_master',
    title: 'コーヒーブレイクマスター',
    description: '20回の休憩セッションを完了する',
    icon: Coffee,
    iconColor: '#6F4E37',
    requiredValue: 20,
    type: 'sessions',
    reward: 150,
  },
  {
    id: 'rest_and_recover',
    title: '休息と回復',
    description: '50回の休憩セッションを完了する',
    icon: Coffee,
    iconColor: '#8B4513',
    requiredValue: 50,
    type: 'sessions',
    reward: 250,
  },
  
  // 特殊実績
  {
    id: 'star_achiever',
    title: 'スター達成者',
    description: '5つの実績を解除する',
    icon: Star,
    iconColor: colors.warning,
    requiredValue: 5,
    type: 'specialAction',
    reward: 200,
  },
  {
    id: 'achievement_hunter',
    title: '実績ハンター',
    description: '10つの実績を解除する',
    icon: Star,
    iconColor: '#FFD700',
    requiredValue: 10,
    type: 'specialAction',
    reward: 300,
  },
  {
    id: 'achievement_collector',
    title: '実績コレクター',
    description: '20つの実績を解除する',
    icon: Star,
    iconColor: '#FFA500',
    requiredValue: 20,
    type: 'specialAction',
    reward: 500,
  },
  
  // 継続日数関連
  {
    id: 'first_day',
    title: '初日',
    description: '初めての日にポモドーロを完了する',
    icon: Compass,
    iconColor: colors.primary,
    requiredValue: 1,
    type: 'totalDays',
    reward: 50,
  },
  {
    id: 'week_warrior',
    title: 'ウィークウォリアー',
    description: '7日間（連続でなくても）ポモドーロを完了する',
    icon: Dumbbell,
    iconColor: colors.secondary,
    requiredValue: 7,
    type: 'totalDays',
    reward: 150,
  },
  {
    id: 'month_master',
    title: 'マンスマスター',
    description: '30日間（連続でなくても）ポモドーロを完了する',
    icon: Medal,
    iconColor: colors.warning,
    requiredValue: 30,
    type: 'totalDays',
    reward: 300,
  },
  
  // 特殊な実績（隠し実績）
  {
    id: 'night_owl',
    title: 'ナイトオウル',
    description: '夜22時以降にポモドーロセッションを完了する',
    icon: Lightbulb,
    iconColor: '#FFD700',
    requiredValue: 1,
    type: 'specialAction',
    reward: 100,
    secret: true,
  },
  {
    id: 'early_bird',
    title: 'アーリーバード',
    description: '朝6時前にポモドーロセッションを完了する',
    icon: Lightbulb,
    iconColor: '#87CEEB',
    requiredValue: 1,
    type: 'specialAction',
    reward: 100,
    secret: true,
  },
  {
    id: 'weekend_warrior',
    title: 'ウィークエンドウォリアー',
    description: '週末（土日）に5回のポモドーロセッションを完了する',
    icon: Rocket,
    iconColor: colors.primary,
    requiredValue: 5,
    type: 'specialAction',
    reward: 150,
    secret: true,
  },
  {
    id: 'holiday_hustler',
    title: 'ホリデーハスラー',
    description: '祝日にポモドーロセッションを完了する',
    icon: Gift,
    iconColor: '#FF69B4',
    requiredValue: 1,
    type: 'specialAction',
    reward: 100,
    secret: true,
  },
  {
    id: 'marathon_master',
    title: 'マラソンマスター',
    description: '1日に10回以上のポモドーロセッションを完了する',
    icon: Rocket,
    iconColor: '#FF4500',
    requiredValue: 10,
    type: 'specialAction',
    reward: 200,
    secret: true,
  },
  {
    id: 'perfect_week',
    title: 'パーフェクトウィーク',
    description: '1週間連続で毎日少なくとも4回のポモドーロを完了する',
    icon: Sparkles,
    iconColor: '#FFD700',
    requiredValue: 7,
    type: 'specialAction',
    reward: 300,
    secret: true,
  },
  {
    id: 'brain_booster',
    title: 'ブレインブースター',
    description: '合計5000分の集中時間を達成する',
    icon: Brain,
    iconColor: '#9370DB',
    requiredValue: 5000,
    type: 'totalMinutes',
    reward: 500,
  },
  {
    id: 'focus_fanatic',
    title: 'フォーカスファナティック',
    description: '合計200回のポモドーロセッションを完了する',
    icon: Gem,
    iconColor: '#4169E1',
    requiredValue: 200,
    type: 'sessions',
    reward: 500,
  },
  {
    id: 'pomodoro_pioneer',
    title: 'ポモドーロパイオニア',
    description: 'アプリを30日間使用する（連続でなくても）',
    icon: Heart,
    iconColor: colors.error,
    requiredValue: 30,
    type: 'totalDays',
    reward: 300,
  },
  {
    id: 'pomodoro_veteran',
    title: 'ポモドーロベテラン',
    description: 'アプリを90日間使用する（連続でなくても）',
    icon: Heart,
    iconColor: '#FF1493',
    requiredValue: 90,
    type: 'totalDays',
    reward: 500,
  },
  // 新しい実績を追加
  {
    id: 'morning_routine',
    title: 'モーニングルーティン',
    description: '朝6時から9時の間に5回のポモドーロセッションを完了する',
    icon: Coffee,
    iconColor: '#FFA500',
    requiredValue: 5,
    type: 'specialAction',
    reward: 150,
    secret: true,
  },
  {
    id: 'lunch_break_hero',
    title: 'ランチブレイクヒーロー',
    description: '昼休み（12時から13時）にポモドーロセッションを完了する',
    icon: Coffee,
    iconColor: '#32CD32',
    requiredValue: 1,
    type: 'specialAction',
    reward: 100,
    secret: true,
  },
  {
    id: 'evening_scholar',
    title: '夕方の学者',
    description: '夕方（17時から20時）に10回のポモドーロセッションを完了する',
    icon: Lightbulb,
    iconColor: '#9932CC',
    requiredValue: 10,
    type: 'specialAction',
    reward: 200,
    secret: true,
  },
  {
    id: 'weekend_marathon',
    title: 'ウィークエンドマラソン',
    description: '週末の1日で15回以上のポモドーロセッションを完了する',
    icon: Rocket,
    iconColor: '#FF6347',
    requiredValue: 15,
    type: 'specialAction',
    reward: 300,
    secret: true,
  },
  {
    id: 'golden_ratio',
    title: 'ゴールデンレシオ',
    description: '1日で8回のポモドーロセッションを完了する',
    icon: Star,
    iconColor: '#FFD700',
    requiredValue: 8,
    type: 'specialAction',
    reward: 150,
  },
  {
    id: 'focus_flow',
    title: 'フォーカスフロー',
    description: '4回連続でポモドーロセッションを中断せずに完了する',
    icon: Zap,
    iconColor: '#00BFFF',
    requiredValue: 4,
    type: 'specialAction',
    reward: 200,
  },
  {
    id: 'deep_work',
    title: 'ディープワーク',
    description: '1日で合計120分以上の集中時間を達成する',
    icon: Brain,
    iconColor: '#4682B4',
    requiredValue: 120,
    type: 'specialAction',
    reward: 250,
  },
  {
    id: 'focus_samurai',
    title: 'フォーカス侍',
    description: '500回のポモドーロセッションを完了する',
    icon: Gem,
    iconColor: '#B22222',
    requiredValue: 500,
    type: 'sessions',
    reward: 1000,
  },
  {
    id: 'time_traveler',
    title: 'タイムトラベラー',
    description: '合計10000分の集中時間を達成する',
    icon: Clock,
    iconColor: '#483D8B',
    requiredValue: 10000,
    type: 'totalMinutes',
    reward: 1000,
  },
  {
    id: 'pomodoro_legend',
    title: 'ポモドーロレジェンド',
    description: 'アプリを365日間使用する（連続でなくても）',
    icon: Crown,
    iconColor: '#FFD700',
    requiredValue: 365,
    type: 'totalDays',
    reward: 1000,
  },
  {
    id: 'focus_streak_master',
    title: 'フォーカスストリークマスター',
    description: '60日間の連続記録を達成する',
    icon: Flame,
    iconColor: '#FF4500',
    requiredValue: 60,
    type: 'streak',
    reward: 800,
  },
  {
    id: 'focus_streak_legend',
    title: 'フォーカスストリークレジェンド',
    description: '100日間の連続記録を達成する',
    icon: Flame,
    iconColor: '#FF0000',
    requiredValue: 100,
    type: 'streak',
    reward: 1500,
  },
  {
    id: 'character_evolution_1',
    title: '最初の進化',
    description: 'キャラクターを初めて進化させる',
    icon: Sparkles,
    iconColor: '#9370DB',
    requiredValue: 2,
    type: 'specialAction',
    reward: 200,
  },
  {
    id: 'character_evolution_2',
    title: '第二進化',
    description: 'キャラクターをレベル3まで進化させる',
    icon: Sparkles,
    iconColor: '#4169E1',
    requiredValue: 3,
    type: 'specialAction',
    reward: 300,
  },
  {
    id: 'character_evolution_3',
    title: '第三進化',
    description: 'キャラクターをレベル4まで進化させる',
    icon: Sparkles,
    iconColor: '#FF1493',
    requiredValue: 4,
    type: 'specialAction',
    reward: 400,
  },
  {
    id: 'character_evolution_4',
    title: '最終進化',
    description: 'キャラクターを最終形態まで進化させる',
    icon: Sparkles,
    iconColor: '#FFD700',
    requiredValue: 5,
    type: 'specialAction',
    reward: 500,
  },
  {
    id: 'minigame_master',
    title: 'ミニゲームマスター',
    description: '休憩中のミニゲームで高得点を達成する',
    icon: Smile,
    iconColor: '#32CD32',
    requiredValue: 1,
    type: 'specialAction',
    reward: 100,
    secret: true,
  },
  {
    id: 'balanced_character',
    title: 'バランス型マスター',
    description: 'バランス型のキャラクターを育成する',
    icon: Medal,
    iconColor: colors.primary,
    requiredValue: 1,
    type: 'specialAction',
    reward: 200,
  },
  {
    id: 'focused_character',
    title: '集中型マスター',
    description: '集中型のキャラクターを育成する',
    icon: Medal,
    iconColor: colors.secondary,
    requiredValue: 1,
    type: 'specialAction',
    reward: 200,
  },
  {
    id: 'consistent_character',
    title: '継続型マスター',
    description: '継続型のキャラクターを育成する',
    icon: Medal,
    iconColor: colors.warning,
    requiredValue: 1,
    type: 'specialAction',
    reward: 200,
  },
  
  // ミニゲーム関連の実績
  {
    id: 'game_explorer',
    title: 'ゲームエクスプローラー',
    description: '3種類のミニゲームをプレイする',
    icon: GamepadIcon,
    iconColor: colors.secondary,
    requiredValue: 3,
    type: 'specialAction',
    reward: 150,
  },
  {
    id: 'game_enthusiast',
    title: 'ゲーム愛好家',
    description: '全てのミニゲームをプレイする',
    icon: GamepadIcon,
    iconColor: colors.primary,
    requiredValue: 7,
    type: 'specialAction',
    reward: 300,
  },
  {
    id: 'tap_master',
    title: 'タップマスター',
    description: 'タップターゲットゲームで30点以上獲得する',
    icon: Target,
    iconColor: colors.primary,
    requiredValue: 30,
    type: 'gameScore',
    reward: 100,
  },
  {
    id: 'memory_master',
    title: 'メモリーマスター',
    description: 'メモリーマッチゲームで80点以上獲得する',
    icon: Brain,
    iconColor: colors.secondary,
    requiredValue: 80,
    type: 'gameScore',
    reward: 150,
  },
  {
    id: 'puzzle_master',
    title: 'パズルマスター',
    description: '数字パズルゲームで150点以上獲得する',
    icon: Brain,
    iconColor: colors.success,
    requiredValue: 150,
    type: 'gameScore',
    reward: 200,
  },
  {
    id: 'pattern_memory_master',
    title: 'パターン記憶の達人',
    description: 'パターンメモリーゲームでレベル5をクリアする',
    icon: Brain,
    iconColor: colors.warning,
    requiredValue: 1,
    type: 'specialAction',
    reward: 200,
  },
  {
    id: 'word_master',
    title: '単語マスター',
    description: '単語スクランブルゲームで50点以上獲得する',
    icon: Brain,
    iconColor: colors.primary,
    requiredValue: 50,
    type: 'gameScore',
    reward: 150,
  },
  {
    id: 'math_genius',
    title: '計算の天才',
    description: '計算チャレンジゲームで30点以上獲得する',
    icon: Brain,
    iconColor: colors.error,
    requiredValue: 30,
    type: 'gameScore',
    reward: 200,
  },
  {
    id: 'color_master',
    title: 'カラーマスター',
    description: 'カラーマッチゲームで25点以上獲得する',
    icon: Brain,
    iconColor: '#9370DB',
    requiredValue: 25,
    type: 'gameScore',
    reward: 150,
  },
  {
    id: 'game_addict',
    title: 'ゲーム中毒',
    description: 'ミニゲームを合計50回プレイする',
    icon: GamepadIcon,
    iconColor: '#FF4500',
    requiredValue: 50,
    type: 'specialAction',
    reward: 300,
  },
  {
    id: 'break_time_champion',
    title: '休憩時間チャンピオン',
    description: '全てのミニゲームでハイスコアを更新する',
    icon: Trophy,
    iconColor: '#FFD700',
    requiredValue: 7,
    type: 'specialAction',
    reward: 500,
  },
  
  // 新しい実績
  {
    id: 'early_riser_week',
    title: '早起き週間',
    description: '1週間連続で朝8時前にポモドーロを完了する',
    icon: Lightbulb,
    iconColor: '#FFA500',
    requiredValue: 7,
    type: 'specialAction',
    reward: 250,
    secret: true,
  },
  {
    id: 'night_study_session',
    title: '夜間学習セッション',
    description: '夜10時以降に3回連続でポモドーロを完了する',
    icon: Lightbulb,
    iconColor: '#483D8B',
    requiredValue: 3,
    type: 'specialAction',
    reward: 150,
    secret: true,
  },
  {
    id: 'seasonal_studier_spring',
    title: '春の勉強家',
    description: '春の間に100回のポモドーロを完了する',
    icon: Rocket,
    iconColor: '#FF69B4',
    requiredValue: 100,
    type: 'specialAction',
    reward: 300,
    secret: true,
  },
  {
    id: 'seasonal_studier_summer',
    title: '夏の勉強家',
    description: '夏の間に100回のポモドーロを完了する',
    icon: Rocket,
    iconColor: '#FFD700',
    requiredValue: 100,
    type: 'specialAction',
    reward: 300,
    secret: true,
  },
  {
    id: 'seasonal_studier_autumn',
    title: '秋の勉強家',
    description: '秋の間に100回のポモドーロを完了する',
    icon: Rocket,
    iconColor: '#FF8C00',
    requiredValue: 100,
    type: 'specialAction',
    reward: 300,
    secret: true,
  },
  {
    id: 'seasonal_studier_winter',
    title: '冬の勉強家',
    description: '冬の間に100回のポモドーロを完了する',
    icon: Rocket,
    iconColor: '#87CEEB',
    requiredValue: 100,
    type: 'specialAction',
    reward: 300,
    secret: true,
  },
  {
    id: 'focus_machine',
    title: 'フォーカスマシーン',
    description: '1日で合計240分（4時間）の集中時間を達成する',
    icon: Brain,
    iconColor: '#FF4500',
    requiredValue: 240,
    type: 'specialAction',
    reward: 400,
  },
  {
    id: 'pomodoro_addict',
    title: 'ポモドーロ中毒',
    description: '1000回のポモドーロセッションを完了する',
    icon: Crown,
    iconColor: '#FF0000',
    requiredValue: 1000,
    type: 'sessions',
    reward: 2000,
  },
  {
    id: 'focus_deity',
    title: '集中の神',
    description: '合計20000分（333時間）の集中時間を達成する',
    icon: Sparkles,
    iconColor: '#FFD700',
    requiredValue: 20000,
    type: 'totalMinutes',
    reward: 2000,
  },
  {
    id: 'character_collector',
    title: 'キャラクターコレクター',
    description: '3種類の異なるキャラクターを育成する',
    icon: Award,
    iconColor: colors.primary,
    requiredValue: 3,
    type: 'specialAction',
    reward: 500,
  },
  {
    id: 'evolution_master',
    title: '進化マスター',
    description: 'キャラクターを最終進化まで育てる',
    icon: Star,
    iconColor: '#FFD700',
    requiredValue: 1,
    type: 'specialAction',
    reward: 1000,
  },
  {
    id: 'pomodoro_millionaire',
    title: 'ポモドーロミリオネア',
    description: '合計1000000XPを獲得する',
    icon: Gem,
    iconColor: '#4169E1',
    requiredValue: 1000000,
    type: 'specialAction',
    reward: 5000,
  },
  
  // チームセッション関連の実績
  {
    id: 'first_team_session',
    title: '初めてのチームセッション',
    description: '初めてのチームポモドーロセッションを完了する',
    icon: Users,
    iconColor: colors.primary,
    requiredValue: 1,
    type: 'teamSessions',
    reward: 100,
  },
  {
    id: 'team_player',
    title: 'チームプレイヤー',
    description: '5回のチームポモドーロセッションを完了する',
    icon: Users,
    iconColor: colors.secondary,
    requiredValue: 5,
    type: 'teamSessions',
    reward: 200,
  },
  {
    id: 'team_leader',
    title: 'チームリーダー',
    description: '20回のチームポモドーロセッションを完了する',
    icon: Users,
    iconColor: colors.warning,
    requiredValue: 20,
    type: 'teamSessions',
    reward: 300,
  },
  {
    id: 'team_champion',
    title: 'チームチャンピオン',
    description: '50回のチームポモドーロセッションを完了する',
    icon: Users,
    iconColor: '#FFD700',
    requiredValue: 50,
    type: 'teamSessions',
    reward: 500,
  },
  {
    id: 'team_hour',
    title: 'チーム1時間',
    description: 'チームセッションで合計1時間を達成する',
    icon: Clock,
    iconColor: colors.primary,
    requiredValue: 60,
    type: 'teamMinutes',
    reward: 150,
  },
  {
    id: 'team_5_hours',
    title: 'チーム5時間',
    description: 'チームセッションで合計5時間を達成する',
    icon: Clock,
    iconColor: colors.secondary,
    requiredValue: 300,
    type: 'teamMinutes',
    reward: 300,
  },
  {
    id: 'team_master',
    title: 'チームマスター',
    description: 'チームセッションで合計1000分（16.6時間）を達成する',
    icon: Clock,
    iconColor: '#FFD700',
    requiredValue: 1000,
    type: 'teamMinutes',
    reward: 500,
  },
];

export const getAchievementProgress = (
  achievement: Achievement,
  userStats: {
    sessions: number;
    streak: number;
    totalMinutes: number;
    level: number;
    unlockedAchievements: string[];
    totalDays: number;
    totalSessions: number;
    teamSessionsCompleted: number;
    teamSessionMinutes: number;
  }
) => {
  let currentValue = 0;
  
  switch (achievement.type) {
    case 'sessions':
      currentValue = userStats.sessions;
      break;
    case 'streak':
      currentValue = userStats.streak;
      break;
    case 'totalMinutes':
      currentValue = userStats.totalMinutes;
      break;
    case 'level':
      currentValue = userStats.level;
      break;
    case 'totalDays':
      currentValue = userStats.totalDays;
      break;
    case 'totalSessions':
      currentValue = userStats.totalSessions;
      break;
    case 'teamSessions':
      currentValue = userStats.teamSessionsCompleted;
      break;
    case 'teamMinutes':
      currentValue = userStats.teamSessionMinutes;
      break;
    case 'specialAction':
      // Special cases
      if (achievement.id === 'star_achiever' || achievement.id === 'achievement_hunter' || achievement.id === 'achievement_collector') {
        currentValue = userStats.unlockedAchievements.length;
      }
      break;
    case 'gameScore':
      // Game scores are handled separately
      currentValue = 0;
      break;
  }
  
  const progress = Math.min(currentValue / achievement.requiredValue, 1);
  const isUnlocked = userStats.unlockedAchievements.includes(achievement.id);
  
  return {
    currentValue,
    progress,
    isUnlocked,
  };
};