#!/bin/bash

echo "🔐 Vercel認証エラー解決ガイド"
echo "=============================="
echo ""
echo "現在の問題: HTTP 401 - Vercel Authentication Required"
echo ""
echo "🚨 Vercelプロジェクトに認証保護が有効になっています"
echo ""
echo "📋 解決手順:"
echo "1. Vercelダッシュボードにアクセス"
echo "   https://vercel.com/ivygains-projects/pomomate"
echo ""
echo "2. 設定変更"
echo "   Settings → Deployment Protection"
echo ""
echo "3. 認証を無効化"
echo "   - Password Protection: OFF"
echo "   - Vercel Authentication: OFF"
echo ""
echo "4. 変更を保存"
echo "   Save ボタンをクリック"
echo ""
echo "5. 再デプロイ"
echo "   vercel --prod --force"
echo ""
echo "🔧 現在のデプロイメント状況:"
vercel ls | head -n 8
echo ""
echo "🌐 現在の本番URL:"
echo "https://pomomate-lt8dny1oh-ivygains-projects.vercel.app"
echo ""
echo "この設定変更後、サイトに自由にアクセスできるようになります。" 